<h1>DocOps Draw</h1>
<button class="btn btn-outline btn-info" data-hx-get="boxy.html" data-hx-target="#btns"><i class="fad fa-link text-xs mr-2"></i> Connector</button>
<button class="btn btn-outline btn-info" data-hx-get="pm.html" data-hx-target="#btns"><i class="fad fa-table text-xs mr-2"></i> Placemat</button>
<button class="btn btn-outline btn-info" data-hx-get="json/schema?name=connector-schema" data-hx-target="#btns"><i class="fad fa-link text-xs mr-2"></i> JSON Schema - Connector</button>
<button class="btn btn-outline btn-info" data-hx-get="json/schema?name=placemat-schema" data-hx-target="#btns"><i class="fad fa-table text-xs mr-2"></i> JSON Schema - Placemat</button>

<div id="btns"></div>