PUT http://localhost:8010/extension/api/roadmap/
Content-Length: 286
Content-Type: */*; charset=UTF-8
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

- now
Application Analysis for Resources dependencies. Current and Furture state architecture. Create IAC Config Repository
- now
GitHub branch from current production.
- now
Dockerized Application.
Docker for Desktop required
IaC repository provisioned
- now
Provisioned resources, PVC, Zipkin, Trust Stores, nginx
- now
Pipeline Setup with Devops support. Jenkins work. Automation for building andf linking to IaC for pull requests.
- next
Open Search provision, the back end for zipkin
- next
iBOB process to document data elements for inbound/outbound traffic and thrid party data if any.
- next
Okta, cloud tigers is validating setup
- next
change ingress from application to nginx for API Gateway management
- next
Flight Check
- next
- Release Strategy
- later
network changes to nginx ingress
