PUT http://localhost:8010/extension/api/roadmap/
Content-Length: 286
Content-Type: */*; charset=UTF-8
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

- now
Application Analysis for Resources dependencies. Current and Furture state architecture. Create IAC Config Repository
- now
GitHub branch from current production.
- now
Dockerized Application.
Docker for Desktop required
IaC repository provisioned
- now
Provisioned resources, PVC, Zipkin, Trust Stores, nginx
- now
Pipeline Setup with Devops support. Jenkins work. Automation for building andf linking to IaC for pull requests.
- next
Open Search provision, the back end for zipkin
- next
iBOB process to document data elements for inbound/outbound traffic and thrid party data if any.
- next
Okta, cloud tigers is validating setup
- next
change ingress from application to nginx for API Gateway management
- next
Flight Check
- next
- Release Strategy
- later
network changes to nginx ingress

###

GET http://localhost:8010/extension/api/docops/svg?kind=roadmap&payload=H4sIAAAAAAAA_1VQzU7DMAy-7yn8AqEbQkJwqzSQduBHQ-Iy7eCmXmuRxCVxNvr2pGWTxsGWlXw__mwgyGlRR9uzklXQngCHwbFFZQmQyObIOoKXlhzsdr3qkB6rylPL2d9Y8VUzKk3ViUljUvKmpcRdMOgcY7BUqQxmtTR4scmRjO0xolWKnJRtMkGCOeRgJ1t0JtJ35kiegiZzYu0LgVDT1Mw9tqu7pmmW-NDA6_N2v4ecOHTwVmftbxdmTvUhLs8hrgN57uLfdIjiwVGHdoTBoR4k-jPzZQb9v8RJ4pcTbBOowJCb8gHWSW4vbjpRuvK6CaxcSEeCogn1--YMKRN8UkxFbloWQwtbcoSJ4MweC7KsQnHxdCzJYR2LSoD66nCTFv3oYi0eOcCMS79Zo5TFxwEAAA==&scale=1.0&outlineColor=#7149c6&title=Doestitlepassthrough%3F&numChars=25&type=SVG&useDark=true&filename=docops.svg