# curl 'http://localhost:8010/extension/api/colorgen' -X PUT -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'HX-Request: true' -H 'HX-Target: contentBox' -H 'HX-Current-URL: http://localhost:8010/extension/index.html#close' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Origin: http://localhost:8010' -H 'Connection: keep-alive' -H 'Referer: http://localhost:8010/extension/index.html' -H 'Cookie: Idea-ba6ea630=bc6d4828-c453-4f4f-8bd4-d166b33d7828; Idea-ba6ea9ef=b0a6d26b-200b-41a5-b642-be5b36fd8793; Idea-ba6ea9f0=9ed9272a-e949-4412-a9f7-03eaaa9dac62' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' --data-raw 'points=20&buttonType=LARGE_CARD&columns=3&sortBy=Grouping.TYPE&order=GroupingOrder.ASCENDING'
PUT http://localhost:8010/extension/api/colorgen
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
HX-Request: true
HX-Target: contentBox
HX-Current-URL: http://localhost:8010/extension/index.html#close
Origin: http://localhost:8010
Connection: keep-alive
Referer: http://localhost:8010/extension/index.html
Cookie: Idea-ba6ea630=bc6d4828-c453-4f4f-8bd4-d166b33d7828; Idea-ba6ea9ef=b0a6d26b-200b-41a5-b642-be5b36fd8793; Idea-ba6ea9f0=9ed9272a-e949-4412-a9f7-03eaaa9dac62
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Content-Type: application/x-www-form-urlencoded

points=20&buttonType=LARGE_CARD&columns=3&sortBy=Grouping.TYPE&order=GroupingOrder.ASCENDING

>>! large.html

> {%
client.test("Request executed successfully", function() {
    var type = response.contentType.mimeType;
    client.assert(response.body.indexOf("svg")>0);
    client.assert(type === "text/html", "Expected 'text/html' but received '" + type + "'");
    client.assert(response.status === 202, "Response status is not 202");
});
%}

###

# curl 'http://localhost:8010/extension/api/colorgen' -X PUT -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'HX-Request: true' -H 'HX-Trigger: buttonType' -H 'HX-Trigger-Name: buttonType' -H 'HX-Target: contentBox' -H 'HX-Current-URL: http://localhost:8010/extension/index.html#close' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Origin: http://localhost:8010' -H 'Connection: keep-alive' -H 'Referer: http://localhost:8010/extension/index.html' -H 'Cookie: Idea-ba6ea630=bc6d4828-c453-4f4f-8bd4-d166b33d7828; Idea-ba6ea9ef=b0a6d26b-200b-41a5-b642-be5b36fd8793; Idea-ba6ea9f0=9ed9272a-e949-4412-a9f7-03eaaa9dac62' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' --data-raw 'points=20&buttonType=SLIM_CARD&columns=3&sortBy=Grouping.TYPE&order=GroupingOrder.ASCENDING'
PUT http://localhost:8010/extension/api/colorgen
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
HX-Request: true
HX-Trigger: buttonType
HX-Trigger-Name: buttonType
HX-Target: contentBox
HX-Current-URL: http://localhost:8010/extension/index.html#close
Origin: http://localhost:8010
Connection: keep-alive
Referer: http://localhost:8010/extension/index.html
Cookie: Idea-ba6ea630=bc6d4828-c453-4f4f-8bd4-d166b33d7828; Idea-ba6ea9ef=b0a6d26b-200b-41a5-b642-be5b36fd8793; Idea-ba6ea9f0=9ed9272a-e949-4412-a9f7-03eaaa9dac62
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Content-Type: application/x-www-form-urlencoded

points=20&buttonType=SLIM_CARD&columns=3&sortBy=Grouping.TYPE&order=GroupingOrder.ASCENDING

>>! slim.html

> {%
client.test("Request executed successfully", function() {
    client.assert(response.body.indexOf("svg")>0);
    var type = response.contentType.mimeType;
    client.assert(type === "text/html", "Expected 'text/html' but received '" + type + "'")
    client.assert(response.status === 202, "Response status is not 202");
});
%}

###

# curl 'http://localhost:8010/extension/api/colorgen' -X PUT -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'HX-Request: true' -H 'HX-Trigger: buttonType' -H 'HX-Trigger-Name: buttonType' -H 'HX-Target: contentBox' -H 'HX-Current-URL: http://localhost:8010/extension/index.html#close' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Origin: http://localhost:8010' -H 'Connection: keep-alive' -H 'Referer: http://localhost:8010/extension/index.html' -H 'Cookie: Idea-ba6ea630=bc6d4828-c453-4f4f-8bd4-d166b33d7828; Idea-ba6ea9ef=b0a6d26b-200b-41a5-b642-be5b36fd8793; Idea-ba6ea9f0=9ed9272a-e949-4412-a9f7-03eaaa9dac62' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' --data-raw 'points=8&buttonType=ROUND&columns=3&sortBy=Grouping.TYPE&order=GroupingOrder.ASCENDING'
PUT http://localhost:8010/extension/api/colorgen
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
HX-Request: true
HX-Trigger: buttonType
HX-Trigger-Name: buttonType
HX-Target: contentBox
HX-Current-URL: http://localhost:8010/extension/index.html#close
Origin: http://localhost:8010
Connection: keep-alive
Referer: http://localhost:8010/extension/index.html
Cookie: Idea-ba6ea630=bc6d4828-c453-4f4f-8bd4-d166b33d7828; Idea-ba6ea9ef=b0a6d26b-200b-41a5-b642-be5b36fd8793; Idea-ba6ea9f0=9ed9272a-e949-4412-a9f7-03eaaa9dac62
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Content-Type: application/x-www-form-urlencoded

points=8&buttonType=ROUND&columns=3&sortBy=Grouping.TYPE&order=GroupingOrder.ASCENDING

>>! round.html

> {%
client.test("Request executed successfully", function() {
    client.assert(response.body.indexOf("svg")>0);
    var type = response.contentType.mimeType;
    client.assert(type === "text/html", "Expected 'text/html' but received '" + type + "'")
    client.assert(response.status === 202, "Response status is not 202");
});
%}

###

# curl 'http://localhost:8010/extension/api/colorgen' -X PUT -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'HX-Request: true' -H 'HX-Trigger: buttonType' -H 'HX-Trigger-Name: buttonType' -H 'HX-Target: contentBox' -H 'HX-Current-URL: http://localhost:8010/extension/index.html#close' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Origin: http://localhost:8010' -H 'Connection: keep-alive' -H 'Referer: http://localhost:8010/extension/index.html' -H 'Cookie: Idea-ba6ea630=bc6d4828-c453-4f4f-8bd4-d166b33d7828; Idea-ba6ea9ef=b0a6d26b-200b-41a5-b642-be5b36fd8793; Idea-ba6ea9f0=9ed9272a-e949-4412-a9f7-03eaaa9dac62' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' --data-raw 'points=8&buttonType=BUTTON&columns=3&sortBy=Grouping.TYPE&order=GroupingOrder.ASCENDING'
PUT http://localhost:8010/extension/api/colorgen
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
HX-Request: true
HX-Trigger: buttonType
HX-Trigger-Name: buttonType
HX-Target: contentBox
HX-Current-URL: http://localhost:8010/extension/index.html#close
Origin: http://localhost:8010
Connection: keep-alive
Referer: http://localhost:8010/extension/index.html
Cookie: Idea-ba6ea630=bc6d4828-c453-4f4f-8bd4-d166b33d7828; Idea-ba6ea9ef=b0a6d26b-200b-41a5-b642-be5b36fd8793; Idea-ba6ea9f0=9ed9272a-e949-4412-a9f7-03eaaa9dac62
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Content-Type: application/x-www-form-urlencoded

points=8&buttonType=BUTTON&columns=3&sortBy=Grouping.TYPE&order=GroupingOrder.ASCENDING

>>! panels.html

> {%
client.test("Request executed successfully", function() {
    client.assert(response.body.indexOf("svg")>0);
    var type = response.contentType.mimeType;
    client.assert(type === "text/html", "Expected 'text/html' but received '" + type + "'")
    client.assert(response.status === 202, "Response status is not 202");
});
%}

###

# curl 'http://localhost:8010/extension/api/panelimage' -X PUT -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'HX-Request: true' -H 'HX-Trigger: download' -H 'HX-Trigger-Name: download' -H 'HX-Target: contentBox' -H 'HX-Current-URL: http://localhost:8010/extension/' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Origin: http://localhost:8010' -H 'Connection: keep-alive' -H 'Referer: http://localhost:8010/extension/' -H 'Cookie: Idea-ba6ea630=bc6d4828-c453-4f4f-8bd4-d166b33d7828; Idea-ba6ea9ef=b0a6d26b-200b-41a5-b642-be5b36fd8793; Idea-ba6ea9f0=9ed9272a-e949-4412-a9f7-03eaaa9dac62' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' --data-raw 'fillColor=%23c90076&fontColor=%23eeeeee&download=on&line1=Test%201&line2=&line3='
PUT http://localhost:8010/extension/api/panelimage
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
HX-Request: true
HX-Trigger: download
HX-Trigger-Name: download
HX-Target: contentBox
HX-Current-URL: http://localhost:8010/extension/
Origin: http://localhost:8010
Connection: keep-alive
Referer: http://localhost:8010/extension/
Cookie: Idea-ba6ea630=bc6d4828-c453-4f4f-8bd4-d166b33d7828; Idea-ba6ea9ef=b0a6d26b-200b-41a5-b642-be5b36fd8793; Idea-ba6ea9f0=9ed9272a-e949-4412-a9f7-03eaaa9dac62
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Content-Type: application/x-www-form-urlencoded

fillColor=%23c90076&fontColor=%23eeeeee&download=on&line1=Test%201&line2=For Second&line3=Third Line

### Create badges

PUT http://localhost:8011/extension/api/badge
Content-Type: application/json

[
  {
    "label": "Compelling Offering",
    "message": "300",
    "url": "https://docops.travp.net/solr/Compelling Offering"
  },
  {
    "label": "TMVS",
    "message": "504",
    "url": "https://docops.travp.net/solr/TMVS"
  },
  {
    "label": "Intuitive Experience",
    "message": "120",
    "url": "https://docops.travp.net/solr/Intuitive%20Experience"
  }

]
###

### Metrics
GET http://localhost:8010/extension/actuator/metrics

### docops.panel.generator.color
GET http://localhost:8010/extension/actuator/metrics/docops.panel.generator.color

### docops.panel.image
GET http://localhost:8010/extension/actuator/metrics/docops.panel.image


### docops.panel
GET http://localhost:8011/extension/actuator/metrics/docops.panel


### docops.adr
GET http://localhost:8010/extension/actuator/metrics/docops.adr

### docops.api.ping
GET http://localhost:8011/extension/actuator/metrics/docops.api.ping

### docops.badge
GET http://localhost:8010/extension/api/badge

### docops.badge.put
GET http://localhost:8010/extension/actuator/metrics/docops.badge.put

### docops.badge.get
GET http://localhost:8011/extension/actuator/metrics/docops.badge.get

### badge params
GET http://localhost:8011/extension/api/badge/item?label=Aren't They&message=Cool?&color=RED&amp;filename=abc.svg[format=svg%20,link=%22https://www.yahoo.com%22]