:doctitle: Contributing to DocOps
:project: DocOps Extension Service
:project-name: docops-extension-sever
:project-link: https://github.com/docops-info/docops-extension-sever

We are just getting started at this point, we are looking for community contribution, but still developing what that looks like for this project.  If we have captured your interest please contact link:mailto:info@docops.io[info@docops.io].

== Contributions

=== Feedback

Constructive feedback ad suggestions are always welcome at link:mailto:info@docops.io[info@docops.io].

=== Feature Request

We are still experimenting with the best way to capture feature requests, but for the moment, please feel free to add an issue on the link:{project-link}/issues[{project-name} issue board] and prefix the title with ```Feature: ```.  Otherwise, please send usa message at link:mailto:info@docops.io[info@docops.io].

=== Bug Reports

Please feel free to add an issue on the link:{project-link}/issues[{project-name} issue board] for any bugs you come across.  Please prefix the issue title with ```Bug: ``` and include information on how to recreate the issue, including client input and output information.  Otherwise, please send usa message at link:mailto:info@docops.io[info@docops.io].

=== Code

Please fork this repo, make changes, and submit a pull request for code changes.  Please let us know the intent of the change and the expected result in the pull request.  Additionally, please include appropriate test to validate the contribution.

We will build this out this document in more detail for folks of different skill levels.