openapi: 3.0.3
info:
  title: DocOps Extensions Server
  description: DocOps Extensions Server
  version: 1.0.0
servers:
  - url: 'http://localhost:8010'
paths:
  /:
    get:
      summary: "GET "
      responses:
        "200":
          description: "OK"

  /api/panel:
    get:
      summary: "GET api/panel"
      responses:
        "200":
          description: "OK"
    post:
      summary: "POST api/panel"
      responses:
        "200":
          description: "OK"
  /api/panel/csv:
    post:
      summary: "POST api/panel/csv"
      responses:
        "200":
          description: "OK"
  /api/panel/lines:
    get:
      summary: "GET api/panel/lines"
      responses:
        "200":
          description: "OK"
  /api/ping:
    get:
      summary: "GET api/ping"
      responses:
        "200":
          description: "OK"

  /json/kotlinx-serialization:
    get:
      summary: "GET json/kotlinx-serialization"
      responses:
        "200":
          description: "OK"