openapi: 3.0.3
info:
  title: DocOps Extensions Server
  description: DocOps Extensions Server
  version: 2022.0.0
servers:
  - url: 'http://localhost:8010'
paths:
  /:
    get:
      summary: "GET "
      responses:
        "200":
          description: "OK"

  /api/panel:
    get:
      summary: "GET api/panel"
      parameters:
        - in: query
          name: data
          schema:
            type: string
          required: true
          description: panel data as compressed base64 encoded string
        - in: query
          name: type
          schema:
            type: string
            required: true
            description: type is either PDF or HTML
            default: HTML
          required: true
      responses:
        "200":
          description: "OK"
          content:
            image/svg+xml:
              schema:
                type: string
    post:
      summary: "POST api/panel"
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        "200":
          description: "OK"
          content:
            image/svg+xml:
              schema:
                type: string
  /api/panel/csv:
    post:
      summary: "POST api/panel/csv"
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        "200":
          description: "OK"
          content:
            image/svg+xml:
              schema:
                type: string

  /api/panel/lines:
    get:
      summary: "GET api/panel/lines"
      parameters:
        - in: query
          name: data
          schema:
            type: string
          required: true
          description: panel data as compressed base64 encoded string
      responses:
        "200":
          description: "OK"
  /api/ping:
    get:
      summary: "GET api/ping"
      responses:
        "200":
          description: "OK"

  /json/kotlinx-serialization:
    get:
      summary: "GET json/kotlinx-serialization"
      responses:
        "200":
          description: "OK"
  /api/deflate:
    post:
      summary: "POST api/deflate"
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        "200":
          description: "OK"
  /api/uncompress:
    post:
      summary: "POST api/deflate"
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        "200":
          description: "OK"