<div class="pure-button-group">
    <a id="panelgenerator" data-hx-get="panelgenerator.html" class="pure-button" data-hx-target="#contentBoxPanel">Panel Generator</a>
    <a id="slimpanel" data-hx-get="slimpanel.html" class="pure-button" data-hx-target="#contentBoxPanel" >Slim Panels Editor</a>
    <a id="panelimagebuilder" data-hx-get="panelimagebuilder.html" class="pure-button" data-hx-target="#contentBoxPanel">Panel Image Builder</a>
    <a id="twotoneimagebuilder" data-hx-get="twotoneimagebuilder.html" class="pure-button" data-hx-target="#contentBoxPanel">Two Row Image Builder</a>
    <a id="panelseditor" data-hx-get="panelseditor.html" class="pure-button" data-hx-target="#contentBoxPanel">Panels Editor</a>
</div>

<div id="contentBoxPanel" class="contentBoxPanel"></div>
