<#macro panelsMacro panelgenerator panelimagebuilder twotoneimagebuilder panelseditor>
<a id="panelgenerator" data-hx-get="panelgenerator.html" class="pure-button ${panelgenerator}" data-hx-target="#contentBoxPanel" data-hx-swap-oob="true">Panel Generator</a>
<a id="panelimagebuilder" data-hx-get="panelimagebuilder.html" class="pure-button ${panelimagebuilder}" data-hx-target="#contentBoxPanel" data-hx-swap-oob="true">Panel Image Builder</a>
<a id="twotoneimagebuilder" data-hx-get="twotoneimagebuilder.html" class="pure-button ${twotoneimagebuilder}" data-hx-target="#contentBoxPanel" data-hx-swap-oob="true">Two Row Image Builder</a>
<a id="panelseditor" data-hx-get="panelseditor.html" class="pure-button ${panelseditor}" data-hx-target="#contentBoxPanel" data-hx-swap-oob="true">Panels Editor</a>
</#macro>