<#macro panelsMacro panelgenerator panelimagebuilder twotoneimagebuilder panelseditor slimpanel>
<a id="panelgenerator" data-hx-get="panelgenerator.html" class="btn ${panelgenerator}" data-hx-target="#contentBoxPanel" data-hx-swap-oob="true">Panel Generator</a>
<a id="slimpanel" data-hx-get="slimpanel.html" class="btn ${slimpanel}" data-hx-target="#contentBoxPanel" data-hx-swap-oob="true">Slim Panels Editor</a>
<a id="panelimagebuilder" data-hx-get="panelimagebuilder.html" class="btn ${panelimagebuilder}" data-hx-target="#contentBoxPanel" data-hx-swap-oob="true">Panel Image Builder</a>
<a id="twotoneimagebuilder" data-hx-get="twotoneimagebuilder.html" class="btn ${twotoneimagebuilder}" data-hx-target="#contentBoxPanel" data-hx-swap-oob="true">Two Row Image Builder</a>
<a id="panelseditor" data-hx-get="panelseditor.html" class="btn ${panelseditor}" data-hx-target="#contentBoxPanel" data-hx-swap-oob="true">Panels Editor</a>
</#macro>