<h1>Release Strategies</h1>
<button class="btn btn-outline btn-info" data-hx-get="strat.html" data-hx-target="#btns"><i class="fad fa-link text-xs mr-2"></i> Builder</button>
<button class="btn btn-outline btn-info" data-hx-get="fromJson.html" data-hx-target="#btns"><i class="fad fa-table text-xs mr-2"></i> From JSON</button>
<button class="btn btn-outline btn-info" data-hx-get="json/schema?name=release-strategy-schema" data-hx-target="#btns"><i class="fad fa-link text-xs mr-2"></i> JSON Schema</button>

<div id="btns"></div>