<h1>Release Strategies</h1>

<div role="tablist" class="tabs tabs-boxed">
    <a role="tab" class="tab btnMenu strat" hx-get="strat.html" data-hx-target="#releaseTarget"><i class="fad fa-link text-xs mr-2"></i> Builder</a>
    <a role="tab" class="tab btnMenu fromJson" hx-get="fromJson.html" data-hx-target="#releaseTarget"><i class="fad fa-table text-xs mr-2"></i> From JSON</a>
    <a role="tab" class="tab btnMenu release-strategy-schema" hx-get="json/schema?name=release-strategy-schema" data-hx-target="#releaseTarget"><i class="fad fa-link text-xs mr-2"></i> JSON Schema</a>

</div>

<div id="releaseTarget"></div>