<div class="pure-button-group">
    <a id="chart" class="btn" data-hx-get="chart.html" data-hx-target="#contentBoxPanel">Bar Chart</a>
    <a id="treechart" class="btn" data-hx-get="treechart.html" data-hx-target="#contentBoxPanel">Tree Chart</a>
    <a id="stacked" class="btn" data-hx-get="stacked.html" data-hx-target="#contentBoxPanel">Stacked</a>
    <a id="mychart" class="btn" data-hx-get="mychart.html" data-hx-target="#contentBoxPanel">My Custom EChart</a>
</div>

<div id="contentBoxPanel" class="contentBoxPanel"></div>
