include::_base.adoc[]
= DocOps Buttons Showcase

[abstract]
This document showcases the different types of buttons available in DocOps.


== Buttons

[docops,showcase]
====

[docops,buttons, title="Regular Buttons"]
....
include::data/buttons/buttons1.json[]
....

[docops,buttons, title="PILL Buttons" useDark=true]
....
include::data/buttons/buttons2.json[]
....

[docops,buttons, title="HEX Buttons" ]
....
include::data/buttons/buttons3.json[]
....

[docops,buttons, title="RECTANGLE Buttons" useDark=false]
....
include::data/buttons/buttons4.json[]
....

[docops,buttons, title="RECTANGLE Buttons" useDark=true]
....
include::data/buttons/buttons4b.json[]
....

[docops,buttons, title="CIRCLE Buttons" ]
....
include::data/buttons/buttons5.json[]
....

[docops,buttons, title="LARGE Buttons" ]
....
include::data/buttons/buttons6.json[]
....

[docops,buttons, title="ROUND Buttons" ]
....
include::data/buttons/buttons7.json[]
....

[docops,buttons, title="MORE CIRCLE Buttons" ]
....
include::data/buttons/buttons8.json[]
....

[docops,buttons, title="EVEN MORE PILL Buttons" ]
....
include::data/buttons/buttons9.json[]
....

[docops,buttons, title="HEX Buttons"]
....
include::data/buttons/buttons10.json[]
....

[docops,buttons, title="SLIM buttons"]
....
include::data/buttons/buttons11.json[]
....



[docops,buttons, title="Large Buttons with Social Icons"]
....
{
  "buttons": [
    {
      "label": "Twitter",
      "link": "https://twitter.com",
      "description": "Follow us",
      "type": "social",
      "embeddedImage": {
        "qrEnabled": true
      }
    },
    {
      "label": "Facebook",
      "link": "https://facebook.com",
      "description": "Like our page",
      "type": "social"
    },
    {
      "label": "Instagram",
      "link": "https://instagram.com",
      "description": "See our photos",
      "type": "social",
      "embeddedImage": {
        "qrEnabled": true
      }
    },
    {
      "label": "LinkedIn",
      "link": "https://linkedin.com",
      "description": "Connect with us",
      "type": "social"
    },
    {
      "label": "YouTube",
      "link": "https://youtube.com",
      "description": "Watch our videos",
      "type": "social",
      "embeddedImage": {
        "qrEnabled": true
      }
    }
  ],
  "buttonType": "LARGE",
  "theme": {
    "colors": [
      "#1DA1F2",
      "#4267B2",
      "#E1306C",
      "#0077B5",
      "#FF0000"
    ],
    "colorTypeMap": {
      "social": "#FF0000"
    },
    "columns": 5,
    "scale": 1,
    "sortBy" : {
        "sort": "ORDER"
    }
    "buttonStyle": {
      "labelStyle": "font-family: 'Roboto', sans-serif; font-size: 16px; fill: #ffffff; font-weight: bold; text-anchor: middle;",
      "descriptionStyle": "font-family: 'Roboto', sans-serif; font-size: 10px; fill: #ffffff; text-anchor: middle;"
    }
  }
}
....


====