GET http://localhost:8010/extension/api/docops/png?kind=timeline&payload=H4sIAAAAAAAA_21TS4vbMBC--1dM74k3D1rKXkpgS2mh3cIWelj2IMsTWxtZMiMpjv99Z2Qn-0hvQh7N9_SyqFXEW_iR7AibLdUL2Kw22yLiKd7Cndf3fQA-owvGO3hAOiIBoUUVMIAChwPsUcVEuIA_pkNrHMJPdUAq9p5ABW1M7XX09FzCXxNbfhRM11sEAYFO0SH1UFmvDzD6BFq5QhOvRGCsEXo_IO2ThXjebjrVYCjhq3v244diOWvYpSaFCOuPsX2j4vGxjbEPtzc3k57SeGBGPp-enljNUXW9cQ0MWAXDuIPQTL2srWU0deiiiuxACTtrC58IBk8HHrQWKrzM5oeWj8zjzTsQL34rhzYssi8vnobJU0VsSMuaFRmfAvQ2NUshdeXiRfAD9hG7ih-vQ_xPcCJ0ZtgYNzFmwBe9gvd6NWjvmEtEKoss5WpgW67K1Tl_Hu8m2yYYh2xB9NCZhphgoTkO352VBPkkC6UyjJLF-32-urjBlQpyM87ESfZX3IaDHHSrnCR_ceCeWWX9n99lLk0UPEIpi5RGYPZJelrC9wAmcrFCMJXFgucGktwVWDzxul4Rp5KdnzVYBk7cui8X6F_-OHv_6R32znkGIxhREVuPTkyPreEfSVFsy-JMTrONlThVwjfv61zwV-LuUM8I6ysEl5SFEHmfWHhUOrdskVdMuq06FcrV2X3jsnxON5K3luP9ByqSR3n4AwAA&scale=1.0&outlineColor=%237149c6&title=Demo+timeline+Builder+by+docops.io&numChars=24&type=PDF&useDark=false&filename=docops.png